version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-178-189.compute-1.amazonaws.com
            port: '5432'
            database: d2o5nkhshpdd4n
            ssl: true
            user: ukrqbqbngvcljd
            password: 3881743a9e4f407c663885c0c8abb34acca4863ceca27da5a6d45f1c1c2da117
            migrations: true